
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[constraint]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
"github.com/ipfs/go-detect-race",
"github.com/ipfs/go-ipfs-util",
"github.com/ipfs/go-log",
"github.com/jbenet/goprocess",
"github.com/libp2p/go-conn-security",
"github.com/libp2p/go-conn-security-multistream",
"github.com/libp2p/go-libp2p-blankhost",
"github.com/libp2p/go-libp2p-circuit",
"github.com/libp2p/go-libp2p-interface-connmgr",
"github.com/libp2p/go-libp2p-interface-pnet",
"github.com/libp2p/go-libp2p-loggables",
"github.com/libp2p/go-libp2p-metrics",
"github.com/libp2p/go-libp2p-nat",
"github.com/libp2p/go-libp2p-netutil",
"github.com/libp2p/go-libp2p-protocol",
"github.com/libp2p/go-libp2p-secio",
"github.com/libp2p/go-libp2p-transport",
"github.com/libp2p/go-libp2p-transport-upgrader",
"github.com/libp2p/go-maddr-filter",
"github.com/libp2p/go-stream-muxer",
"github.com/libp2p/go-tcp-transport",
"github.com/libp2p/go-testutil",
"github.com/libp2p/go-ws-transport",
"github.com/multiformats/go-multiaddr-dns",
"github.com/multiformats/go-multiaddr-net",
"github.com/multiformats/go-multistream",
"github.com/whyrusleeping/go-smux-multiplex",
"github.com/whyrusleeping/go-smux-multistream",
"github.com/whyrusleeping/go-smux-yamux",
"github.com/whyrusleeping/mdns"]

ignored = ["github.com/google/protobuf/examples*", "github.com/multiformats/go-multihash/test/sharness/bin"]

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "v1.19.1"


[[constraint]]
  name = "github.com/grpc/grpc-go"
  version = "v1.16.0"


[[constraint]]
  name = "github.com/nebulasio/grpc-gateway"
  branch = "master"


[[constraint]]
  name = "github.com/tecbot/gorocksdb"
  revision = "3e476152774442234f9a9f747386a48a1d82a515"


[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  version = "v6.0.23"


[[constraint]]
  name = "github.com/libp2p/go-stream-muxer"
  version = "v3.0.0"


[[constraint]]
  name = "github.com/whyrusleeping/go-smux-multistream"
  version = "v2.0.2"


[[constraint]]
  name = "github.com/ipfs/go-ipfs-util"
  version = "v1.2.8"


[[constraint]]
  name = "github.com/ipfs/go-log"
  version = "v1.5.7"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-protocol"
  version = "v1.0.0"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-host"
  version = "v3.0.15"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "v2.0.1"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-blankhost"
  version = "v0.3.15"


[[constraint]]
  name = "github.com/multiformats/go-multiaddr-dns"
  version = "v0.2.5"


[[constraint]]
  name = "github.com/jbenet/goprocess"
  branch = "master"


[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  revision = "393301199b4437234bd500b78bdf9555f6428c18"


[[constraint]]
  name = "github.com/libp2p/go-ws-transport"
  version = "v2.0.15"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-metrics"
  version = "v2.1.7"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-swarm"
  version = "v3.0.22"


[[constraint]]
  name = "github.com/whyrusleeping/mdns"
  branch = "master"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-secio"
  version = "v2.0.17"


[[constraint]]
  name = "github.com/libp2p/go-tcp-transport"
  version = "v2.0.16"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-interface-connmgr"
  version = "v0.0.21"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-peerstore"
  version = "v2.0.6"


[[constraint]]
  name = "github.com/libp2p/go-maddr-filter"
  version = "v1.1.10"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-netutil"
  version = "v0.4.12"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-circuit"
  version = "v2.3.2"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  version = "v2.4.0"


[[constraint]]
  name = "github.com/whyrusleeping/go-smux-yamux"
  version = "v2.0.8"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-transport"
  version = "v3.0.15"


[[constraint]]
  name = "github.com/libp2p/go-testutil"
  version = "v1.2.10"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-nat"
  version = "v0.8.8"


[[constraint]]
  name = "github.com/multiformats/go-multistream"
  version = "v0.3.9"


[[constraint]]
  name = "github.com/multiformats/go-multiaddr-net"
  revision = "5b127b903db6848e085c1c2078840d3401f928ef"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-loggables"
  version = "v1.1.24"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-interface-pnet"
  version = "v3.0.0"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-net"
  version = "v3.0.15"


[[constraint]]
  name = "github.com/ipfs/go-detect-race"
  version = "v1.0.1"


[[constraint]]
  name = "github.com/whyrusleeping/go-smux-multiplex"
  version = "v3.0.16"


[[constraint]]
  name = "github.com/libp2p/go-conn-security-multistream"
  version = "v0.1.15"


[[constraint]]
  name = "github.com/libp2p/go-conn-security"
  version = "v0.1.15"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-transport-upgrader"
  version = "v0.1.16"
