
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[constraint]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
"github.com/ipfs/go-detect-race",
"github.com/ipfs/go-ipfs-util",
"github.com/ipfs/go-log",
"github.com/jbenet/goprocess",
"github.com/libp2p/go-conn-security",
"github.com/libp2p/go-conn-security-multistream",
"github.com/libp2p/go-libp2p-blankhost",
"github.com/libp2p/go-libp2p-circuit",
"github.com/libp2p/go-libp2p-interface-connmgr",
"github.com/libp2p/go-libp2p-interface-pnet",
"github.com/libp2p/go-libp2p-loggables",
"github.com/libp2p/go-libp2p-metrics",
"github.com/libp2p/go-libp2p-nat",
"github.com/libp2p/go-libp2p-netutil",
"github.com/libp2p/go-libp2p-protocol",
"github.com/libp2p/go-libp2p-secio",
"github.com/libp2p/go-libp2p-transport",
"github.com/libp2p/go-libp2p-transport-upgrader",
"github.com/libp2p/go-maddr-filter",
"github.com/libp2p/go-stream-muxer",
"github.com/libp2p/go-tcp-transport",
"github.com/libp2p/go-testutil",
"github.com/libp2p/go-ws-transport",
"github.com/multiformats/go-multiaddr-dns",
"github.com/multiformats/go-multiaddr-net",
"github.com/multiformats/go-multistream",
"github.com/whyrusleeping/go-smux-multiplex",
"github.com/whyrusleeping/go-smux-multistream",
"github.com/whyrusleeping/go-smux-yamux",
"github.com/whyrusleeping/mdns",
"github.com/libp2p/go-libp2p-autonat",
"github.com/libp2p/go-libp2p-discovery",
"github.com/libp2p/go-libp2p-routing"]

ignored = ["github.com/google/protobuf/examples*", "github.com/multiformats/go-multihash/test/sharness/bin"]

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "v1.19.1"


[[constraint]]
  name = "github.com/grpc/grpc-go"
  version = "v1.16.0"


[[constraint]]
  name = "github.com/nebulasio/grpc-gateway"
  branch = "master"


[[constraint]]
  name = "github.com/tecbot/gorocksdb"
  revision = "3e476152774442234f9a9f747386a48a1d82a515"


[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  revision = "768598b353be264ce8420be6353d753a654967ee"


[[constraint]]
  name = "github.com/libp2p/go-stream-muxer"
  revision = "740c590020d83cffa5a092f6a08901ff0d96cc93"


[[constraint]]
  name = "github.com/whyrusleeping/go-smux-multistream"
  revision = "e799b10bc6eea2cc5ce18f7b7b4d8e1a0439476d"


[[constraint]]
  name = "github.com/ipfs/go-ipfs-util"
  revision = "05b6094b6fa9c1e49b4b941061fdc147db1a21b7"


[[constraint]]
  name = "github.com/ipfs/go-log"
  revision = "de9a213953d6ec0e053b56e9d79800565c3fc9ca"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-protocol"
  revision = "e34f0d7468b3519bf9bf4e43c1d028ce651eab51"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-host"
  revision = "735fd0a7fb546a35b903c8eae76b9184fcb6870c"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  revision = "3120e9f9526fe05f2d3905961a5e0701b85579d9"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-blankhost"
  revision = "aad3e0bcd0c2df6a8ae4d319a23ef0e003b5a1f8"


[[constraint]]
  name = "github.com/multiformats/go-multiaddr-dns"
  revision = "b3d6340f0777006db9e16e2817745c52fd64a500"


[[constraint]]
  name = "github.com/jbenet/goprocess"
  revision = "b497e2f366b8624394fb2e89c10ab607bebdde0b"


[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  revision = "8c3eb5dc1c12c5723d5b1d7de82abfa0e6f719d7"


[[constraint]]
  name = "github.com/libp2p/go-ws-transport"
  revision = "cf837a525caf2b39044564847d8cf04b7734717c"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-metrics"
  revision = "623fc2e95e2bd3143caa442b03121b60cc45b76d"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-swarm"
  revision = "4aa22e840e2abc934b768c315f284dfa8a7fb2b7"


[[constraint]]
  name = "github.com/whyrusleeping/mdns"
  revision = "abf6f240934d687d4dff1c31dfbf94c28be9efda"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-secio"
  revision = "a32a62ac3b6290558da74665995ce8cd0a891b6d"


[[constraint]]
  name = "github.com/libp2p/go-tcp-transport"
  revision = "b798b13b16f2e0bd49085c8cd4f5f83394d8a8ab"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-interface-connmgr"
  revision = "c31495968b1bb44bd8a59d5cb33369186611771b"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-peerstore"
  revision = "23d213ec8cefd793a3ec50b4198f91974ec9e70b"


[[constraint]]
  name = "github.com/libp2p/go-maddr-filter"
  revision = "d7110fe4b673d43d05960985eb0d04e69c02f896"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-netutil"
  revision = "52aaa5543b0fc6baa29a45637e25f722c570ff05"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-circuit"
  revision = "fd7f6bb06d860a8d1cc9e4beef28b95d7dce2c12"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  revision = "403c53bf57131cd1c76719d7e0f33fccd2da1d1d"


[[constraint]]
  name = "github.com/whyrusleeping/go-smux-yamux"
  revision = "49458276a01f7fbc32ff62c8955fa3e852b8e772"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-transport"
  revision = "b3d7bd1776a317359453dc4e09f77be2462997c9"


[[constraint]]
  name = "github.com/libp2p/go-testutil"
  revision = "69a25531324f71977a4f6018fb59fa1c81f6d717"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-nat"
  revision = "9c68cc84c7a70c48a417ff4c9c4aabf498e93742"


[[constraint]]
  name = "github.com/multiformats/go-multistream"
  revision = "0e509f6b999d3be262c0702d25fe868c77de1565"


[[constraint]]
  name = "github.com/multiformats/go-multiaddr-net"
  revision = "c75d1cac17a0d84dbf8b2c53c61f0ebf0575183a"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-loggables"
  revision = "57c325e76872c4459207a136f5310fcdaf0d7899"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-interface-pnet"
  revision = "3eda0a328422c06235501df5be481e4b51edc7cf"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-net"
  revision = "eeeb1a3aa9bcd523d3319db97b54e6d9bd607ced"


[[constraint]]
  name = "github.com/ipfs/go-detect-race"
  revision = "5ea9f55c8a669394da8ff8f23e217366098bf5b6"


[[constraint]]
  name = "github.com/whyrusleeping/go-smux-multiplex"
  revision = "c9680d872b8e73a2fc8d9bba3eacabf1e8add80d"


[[constraint]]
  name = "github.com/libp2p/go-conn-security-multistream"
  revision = "eb108e0882d551a411b1c615ea755e3029354b78"


[[constraint]]
  name = "github.com/libp2p/go-conn-security"
  revision = "4bd49438bc6d6b9cc7343d3bb36e878cf7d1138e"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-transport-upgrader"
  revision = "c70e773d05162124ac32cece7b2c3756832e5756"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-autonat"
  revision = "0877e8d474b5e1d69aed583dda3b9ba992978ba1"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-discovery"
  revision = "dd03021a71b32b1efb6dc5d1cc6127c69ce73a3c"


[[constraint]]
  name = "github.com/libp2p/go-libp2p-routing"
  revision = "4e8066d30291d90c8f25ae14152faffaf473839f"